name: Setup-Zig-Example

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  example:
    name: Install tooling
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: temurin
          java-version: 21.0.4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          cache: false
          target: x86_64-pc-windows-msvc # additional target, Linux/Mac targets are configured as default

      - name: Setup Zig (Linux/Mac cross-compile)
        uses: mlugg/setup-zig@a67e68dc5c8281d9608136d3d7ca1b282213e4ac  # v1.2.1
        with:
          use-cache: 'false'

      - name: Setup lld (Windows cross-compile)
        run: |
          sudo apt-get update
          sudo apt-get -y install lld

      - name: Echo Finish
        run: echo "Finished Run! Zig, LLD, and Rust are all installed"